/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.Controlador_FRM_MantenimientoClientes;
import Modelo.Clientes;
import Modelo.ConexionBD;

/**
 *
 * @author Fabricio Vargas
 */
public class FRM_MantenimientoClientes extends javax.swing.JFrame {

   public  Controlador_FRM_MantenimientoClientes controlador_frm_mantenimientoClientes;
    
    /**
     * Creates new form FRM_MantenimientoClientes
     */
    
    public FRM_MantenimientoClientes(ConexionBD conexion) {
        initComponents();
         setLocationRelativeTo(null);
         controlador_frm_mantenimientoClientes= new Controlador_FRM_MantenimientoClientes(this, conexion);
          jP_Botones1.agregarEventosClientes(controlador_frm_mantenimientoClientes);
        btn_ReporteClientes.addActionListener(controlador_frm_mantenimientoClientes);
    }
    
    public Clientes devolverInformacion()
    {
      return jP_InformacionClientes1.devolverInformacion();
    }//Fin metodo devolverInformacion
    
    public String devolverCedula()
    {
      return jP_InformacionClientes1.devolverCedula();
    }//Fin metodo devolver codigo
    
    public void mostrarInformacion(Clientes cliente)
    {
        jP_InformacionClientes1.mostrarInformacion(cliente);
    }//Fin metodo mostrar informacion
    
    public void habilitarAgregar()
    {
        jP_InformacionClientes1.habilitarAgregar();
        jP_Botones1.habilitarAgregar();
    }//Fin metodo habilitarAgregar
    public void estadoInicial()
    {
      jP_InformacionClientes1.estadoInicial();
      jP_Botones1.estadoInicial();
    }//Fin metodo estado inicial
    
    public void habilitarModificarEliminar()
    {
        jP_InformacionClientes1.habilitarAgregar();
        jP_Botones1.habilitarModificarEliminar();
    }//Fin metodo habilitarModificarEliminar

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_InformacionClientes1 = new Vista.JP_InformacionClientes();
        jP_Botones1 = new Vista.JP_Botones();
        btn_ReporteClientes = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btn_ReporteClientes.setText("Reporte");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jP_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jP_InformacionClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ReporteClientes)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_InformacionClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btn_ReporteClientes)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jP_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ReporteClientes;
    private Vista.JP_Botones jP_Botones1;
    private Vista.JP_InformacionClientes jP_InformacionClientes1;
    // End of variables declaration//GEN-END:variables
}
