


package Vista;

import Controlador.Controlador_FRM_MantenimientoUsuarios;
import Modelo.ConexionBD;
import Modelo.Usuario;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fabricio Vargas
 */
public class FRM_MantenimientoAdministracionUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MantenimientoAdministracionUsuarios
     */
    
    public Controlador_FRM_MantenimientoUsuarios controlador;
    String columnas[];
    DefaultTableModel modelo;
    ConexionBD conexion;
    public FRM_MantenimientoAdministracionUsuarios(ConexionBD conexion) 
    {
        initComponents();
        
       controlador= new Controlador_FRM_MantenimientoUsuarios(this, conexion);
        jP_Botones1.agregarEventosUsuarios(controlador);
        modelo = new DefaultTableModel();
        columnas= new String [4];
        columnas[0]="Usuario";
        columnas[1]="Contraseña";
        columnas[2]="Nombre Completo";
        columnas[3]="Tipo";
        jtbl_Clientes.setModel(modelo);
        jtbl_Clientes.addMouseListener(controlador);
        setLocationRelativeTo(null);
       
    }
    
    
    public void cargarInformacion(String matriz[][])
    {
       modelo.setDataVector(matriz, columnas);
    }
    
    public String devolverUsuario()
    {
        return ""+modelo.getValueAt(jtbl_Clientes.getSelectedRow(), 0);
        
    }
    public void estadoInicial()
    {
        jP_Botones1.estadoInicial();
        jP_InformacionAdministracionUsuarios1.estadoInicial();
    }
    public void hablitarAgregar()
    {
        jP_Botones1.habilitarAgregar();
        jP_InformacionAdministracionUsuarios1.habilitarAgregar();
    }
    public Usuario devolverInfo()
    {
       return jP_InformacionAdministracionUsuarios1.devolverInformacion();
    }
    public  void habilitarModificarEliminar()
    {
      jP_Botones1.habilitarModificarEliminar();        
        jP_InformacionAdministracionUsuarios1.habilitarAgregar();
    }
    
    public String devolverNombreUsuario()
    {
        return jP_InformacionAdministracionUsuarios1.devolverUsuario();
    }
    
    public void mostrarInformacion(Usuario usuario)
    {
        jP_InformacionAdministracionUsuarios1.mostrarInfromacion(usuario);
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_InformacionAdministracionUsuarios1 = new Vista.JP_InformacionAdministracionUsuarios();
        jP_Botones1 = new Vista.JP_Botones();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_Clientes = new javax.swing.JTable();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jtbl_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Usuario", "Contraseña", "Nombre Completo", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(jtbl_Clientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Botones1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jP_InformacionAdministracionUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jP_InformacionAdministracionUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
 
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.JP_Botones jP_Botones1;
    private Vista.JP_InformacionAdministracionUsuarios jP_InformacionAdministracionUsuarios1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbl_Clientes;
    // End of variables declaration//GEN-END:variables
}
