

package Vista;

import Controlador.Controlador_FRM_MantenimientoClientes;
import javax.swing.table.DefaultTableModel;


public class FRM_ReporteClientes extends javax.swing.JFrame {

    DefaultTableModel modelo;
    String vector[];
    
    /**
     * Creates new form FRM_ReporteClientes
     */
    public FRM_ReporteClientes(Controlador_FRM_MantenimientoClientes controlador) {
        initComponents();
         setLocation(800,200);
        modelo = new DefaultTableModel();
        vector = new String [3];
        vector[0]="Cedula";
        vector[1]="Nombre";
        vector[2]="Telefono";
        jtbl_ReporteClientes.setModel(modelo);
        jtbl_ReporteClientes.addMouseListener(controlador);
    }
    public void cargarInformacion(String matrizInformacion[][])
    {
        modelo.setDataVector(matrizInformacion, vector);
    }
    
    public String devolverCedula()
    {
         return ""+modelo.getValueAt(jtbl_ReporteClientes.getSelectedRow(), 0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_ReporteClientes = new javax.swing.JTable();

        jtbl_ReporteClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtbl_ReporteClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbl_ReporteClientes;
    // End of variables declaration//GEN-END:variables
}
