
package Vista;

import Controlador.Contrlador_FRM_MenuPrincipal;
import Controlador.Controlador_FRM_Login;
import Modelo.ConexionBD;
import controlador.ArchivosBaseDtos;


public class FRM_MenuPrincipal extends javax.swing.JFrame {

    FRM_Login frm_Login;
    Contrlador_FRM_MenuPrincipal controlador;    
    public FRM_MenuPrincipal() {
        initComponents();
//        archivos.recargarArchivos();
        setSize(1000,700);
        setLocationRelativeTo(null);
        controlador= new Contrlador_FRM_MenuPrincipal(this);
        jmi_Caja.addActionListener(controlador);
        jmi_Facturacion.addActionListener(controlador);
        jmi_Provedores.addActionListener(controlador);
        jmi_Salir.addActionListener(controlador);
        jmi_Cliente.addActionListener(controlador);
        jmi_Manual.addActionListener(controlador);
        jmi_Productos.addActionListener(controlador);
        jmi_Cliente.addActionListener(controlador);
        jmi_AdministracionUsuarios.addActionListener(controlador);
        jmi_cambiarUsuario.addActionListener(controlador);
        jmi_adminBD.addActionListener(controlador);
    }
    
   public void jmiONAdmin(){
        jmi_AdministracionUsuarios.setEnabled(true);
       jmi_Caja.setEnabled(true);
       jmi_Cliente.setEnabled(true);
       jmi_Facturacion.setEnabled(true);
       jmi_Manual.setEnabled(true);
       jmi_Productos.setEnabled(true);
       jmi_Provedores.setEnabled(true);
       jmi_Salir.setEnabled(true);
       jmi_adminBD.setEnabled(true);
       jmi_cambiarUsuario.setEnabled(true);
       
   }
   public void jmiONLogin(){
        jmi_cambiarUsuario.setEnabled(true);       
   }
   
   public void jmiONAdminConexion(){
        jmi_adminBD.setEnabled(true);       
   }
   
    public void jmiONCajeros(){
       jmi_Caja.setEnabled(true);
       jmi_Cliente.setEnabled(true);
       jmi_Facturacion.setEnabled(true);
       jmi_Manual.setEnabled(true);
       jmi_Productos.setEnabled(true);
       jmi_Provedores.setEnabled(true);
       jmi_Salir.setEnabled(true);
       jmi_adminBD.setEnabled(false);
       jmi_cambiarUsuario.setEnabled(true);
       
   }
   
  
    public void cambiarUsuario(){
        controlador.frm_login.limpiar();
        this.setVisible(false);
    
    }
     public void evaluarUsuarios()
    {
        if(Controlador_FRM_Login.tipo.equals("admin")){
            jmi_AdministracionUsuarios.setEnabled(true);
        }else{
            jmi_AdministracionUsuarios.setEnabled(false);
        }
    }
     
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jmb_BarraMenu = new javax.swing.JMenuBar();
        jm_Archivo = new javax.swing.JMenu();
        jmi_cambiarUsuario = new javax.swing.JMenuItem();
        jmi_adminBD = new javax.swing.JMenuItem();
        jmi_Salir = new javax.swing.JMenuItem();
        jm_Mantenimiento = new javax.swing.JMenu();
        jmi_Productos = new javax.swing.JMenuItem();
        jmi_Cliente = new javax.swing.JMenuItem();
        jmi_Provedores = new javax.swing.JMenuItem();
        jmi_AdministracionUsuarios = new javax.swing.JMenuItem();
        jm_Procesos = new javax.swing.JMenu();
        jmi_Facturacion = new javax.swing.JMenuItem();
        jmi_Caja = new javax.swing.JMenuItem();
        jm_Ayuda = new javax.swing.JMenu();
        jmi_Manual = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jm_Archivo.setText("Archivo");

        jmi_cambiarUsuario.setText("Login / Cambiar de usuario");
        jmi_cambiarUsuario.setEnabled(false);
        jmi_cambiarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cambiarUsuarioActionPerformed(evt);
            }
        });
        jm_Archivo.add(jmi_cambiarUsuario);

        jmi_adminBD.setText("Administración BD");
        jmi_adminBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_adminBDActionPerformed(evt);
            }
        });
        jm_Archivo.add(jmi_adminBD);

        jmi_Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jmi_Salir.setText("Salir");
        jm_Archivo.add(jmi_Salir);

        jmb_BarraMenu.add(jm_Archivo);

        jm_Mantenimiento.setText("Mantenimiento");

        jmi_Productos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jmi_Productos.setText("Productos");
        jmi_Productos.setEnabled(false);
        jmi_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ProductosActionPerformed(evt);
            }
        });
        jm_Mantenimiento.add(jmi_Productos);

        jmi_Cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jmi_Cliente.setText("Cliente");
        jmi_Cliente.setEnabled(false);
        jm_Mantenimiento.add(jmi_Cliente);

        jmi_Provedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jmi_Provedores.setText("Provedores");
        jmi_Provedores.setEnabled(false);
        jmi_Provedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ProvedoresActionPerformed(evt);
            }
        });
        jm_Mantenimiento.add(jmi_Provedores);

        jmi_AdministracionUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jmi_AdministracionUsuarios.setText("Administracion de Usuarios");
        jmi_AdministracionUsuarios.setEnabled(false);
        jmi_AdministracionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_AdministracionUsuariosActionPerformed(evt);
            }
        });
        jm_Mantenimiento.add(jmi_AdministracionUsuarios);

        jmb_BarraMenu.add(jm_Mantenimiento);

        jm_Procesos.setText("Procesos");

        jmi_Facturacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jmi_Facturacion.setText("Facturacion");
        jmi_Facturacion.setEnabled(false);
        jmi_Facturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_FacturacionActionPerformed(evt);
            }
        });
        jm_Procesos.add(jmi_Facturacion);

        jmi_Caja.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jmi_Caja.setText("Caja");
        jmi_Caja.setEnabled(false);
        jmi_Caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_CajaActionPerformed(evt);
            }
        });
        jm_Procesos.add(jmi_Caja);

        jmb_BarraMenu.add(jm_Procesos);

        jm_Ayuda.setText("Ayuda");

        jmi_Manual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jmi_Manual.setText("Acerca de");
        jm_Ayuda.add(jmi_Manual);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Manual de usuarios");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jm_Ayuda.add(jMenuItem9);

        jmb_BarraMenu.add(jm_Ayuda);

        setJMenuBar(jmb_BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_ProvedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ProvedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_ProvedoresActionPerformed

    private void jmi_FacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_FacturacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_FacturacionActionPerformed

    private void jmi_CajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_CajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_CajaActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jmi_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_ProductosActionPerformed

    private void jmi_AdministracionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_AdministracionUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_AdministracionUsuariosActionPerformed

    private void jmi_cambiarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cambiarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_cambiarUsuarioActionPerformed

    private void jmi_adminBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_adminBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_adminBDActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String[]args)
   {
      FRM_MenuPrincipal principal= new FRM_MenuPrincipal();     
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jm_Archivo;
    private javax.swing.JMenu jm_Ayuda;
    private javax.swing.JMenu jm_Mantenimiento;
    private javax.swing.JMenu jm_Procesos;
    private javax.swing.JMenuBar jmb_BarraMenu;
    private javax.swing.JMenuItem jmi_AdministracionUsuarios;
    private javax.swing.JMenuItem jmi_Caja;
    private javax.swing.JMenuItem jmi_Cliente;
    private javax.swing.JMenuItem jmi_Facturacion;
    private javax.swing.JMenuItem jmi_Manual;
    private javax.swing.JMenuItem jmi_Productos;
    private javax.swing.JMenuItem jmi_Provedores;
    private javax.swing.JMenuItem jmi_Salir;
    private javax.swing.JMenuItem jmi_adminBD;
    private javax.swing.JMenuItem jmi_cambiarUsuario;
    // End of variables declaration//GEN-END:variables
}
