

package Vista;

import Controlador.Controlador_FRM_MantenimientoProveedores;
import Modelo.ConexionBD;
import Modelo.Proveedores;

public class FRM_MantenimientoProveedores extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MantenimientoProveedores
     */
    
    Controlador_FRM_MantenimientoProveedores controlador_FRM_MantenimientoProveedores;
    public FRM_MantenimientoProveedores(ConexionBD conexion) {
        initComponents();
        setLocationRelativeTo(null);
        controlador_FRM_MantenimientoProveedores=new Controlador_FRM_MantenimientoProveedores(this, conexion);
        btn_ReporteProveedor.addActionListener(controlador_FRM_MantenimientoProveedores);
        jP_Botones1.agregarEventosProveedores(controlador_FRM_MantenimientoProveedores);
    }//Fin constructor
    
    
    public Proveedores devolverInformacion()
    {
        return jP_InformacionProveedores1.devolverInformacion();
    }//Fin metodo devolverInformacion
    
    public String devolverCedula()
    {
        return  jP_InformacionProveedores1.devolverCedula();
    }//Fin metodo devolverCedula
    
    public void habilitarAgregar()
    {
        jP_Botones1.habilitarAgregar();
        jP_InformacionProveedores1.habilitarAgregar();
    }//Fin metodo habilitarAgregar
    
    public void mostrarInformacion(Proveedores provedor)
    {
        jP_InformacionProveedores1.mostrarInformacion(provedor);
       
    }//Fin metodo mostrarInformacion
    
    public void estadoInicial()
    {
        jP_Botones1.estadoInicial();
        jP_InformacionProveedores1.estadoInicial();
    }
    public void habilitarModificarEliminar()
    {
        jP_Botones1.habilitarModificarEliminar();        
        jP_InformacionProveedores1.habilitarAgregar();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_InformacionProveedores1 = new Vista.JP_InformacionProveedores();
        jP_Botones1 = new Vista.JP_Botones();
        btn_ReporteProveedor = new javax.swing.JButton();

        btn_ReporteProveedor.setText("Reporte");
        btn_ReporteProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReporteProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jP_InformacionProveedores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ReporteProveedor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_InformacionProveedores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btn_ReporteProveedor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jP_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ReporteProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReporteProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ReporteProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ReporteProveedor;
    private Vista.JP_Botones jP_Botones1;
    private Vista.JP_InformacionProveedores jP_InformacionProveedores1;
    // End of variables declaration//GEN-END:variables
}
