

package Vista;

import Controlador.Controlador_FRM_MantenimientoUsuarios;
import Controlador.Controlador_FRM_MantenimientoClientes;
import Controlador.Controlador_FRM_MantenimientoProductos;
import Controlador.Controlador_FRM_MantenimientoProveedores;

public class JP_Botones extends javax.swing.JPanel {

    /**
     * Creates new form JP_Botones
     */
    public JP_Botones() {
        initComponents();
    }
    public void agregarEventos(Controlador_FRM_MantenimientoProductos controlador) {
      
        btn_Consulta.addActionListener(controlador);
        btn_Agregar.addActionListener(controlador);
        btn_Eliminar.addActionListener(controlador);
        btn_Modificar.addActionListener(controlador);
    }
    public void agregarEventosProveedores(Controlador_FRM_MantenimientoProveedores controlar) {
      
        btn_Consulta.addActionListener(controlar);
        btn_Agregar.addActionListener(controlar);
        btn_Eliminar.addActionListener(controlar);
        btn_Modificar.addActionListener(controlar);
    }
    
    public void agregarEventosClientes(Controlador_FRM_MantenimientoClientes controlado) {
      
        btn_Consulta.addActionListener(controlado);
        btn_Agregar.addActionListener(controlado);
        btn_Eliminar.addActionListener(controlado);
        btn_Modificar.addActionListener(controlado);
    }
    
    
    public void agregarEventosUsuarios(Controlador_FRM_MantenimientoUsuarios controlado) {
      
        btn_Consulta.addActionListener(controlado);
        btn_Agregar.addActionListener(controlado);
        btn_Eliminar.addActionListener(controlado);
        btn_Modificar.addActionListener(controlado);
    }
    
    
public void habilitarAgregar()
{
        btn_Consulta.setEnabled(false);
        btn_Agregar.setEnabled(true);
        btn_Eliminar.setEnabled(false);
        btn_Modificar.setEnabled(false);
}
public void estadoInicial()
{
    btn_Consulta.setEnabled(true);
    btn_Agregar.setEnabled(false);
    btn_Modificar.setEnabled(false);
    btn_Eliminar.setEnabled(false);
    
}
public void habilitarModificarEliminar()
{
    btn_Consulta.setEnabled(false);
    btn_Agregar.setEnabled(false);
    btn_Modificar.setEnabled(true);
    btn_Eliminar.setEnabled(true); 
}
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Consulta = new javax.swing.JButton();
        btn_Agregar = new javax.swing.JButton();
        btn_Modificar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();

        btn_Consulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/buscar.png"))); // NOI18N
        btn_Consulta.setToolTipText("Consultar");
        btn_Consulta.setActionCommand("Consultar");

        btn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/agregar.png"))); // NOI18N
        btn_Agregar.setToolTipText("Agregar");
        btn_Agregar.setActionCommand("Agregar");
        btn_Agregar.setEnabled(false);

        btn_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/modificar.png"))); // NOI18N
        btn_Modificar.setToolTipText("Modificar");
        btn_Modificar.setActionCommand("Modificar");
        btn_Modificar.setEnabled(false);

        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/eliminar.png"))); // NOI18N
        btn_Eliminar.setToolTipText("Eliminar");
        btn_Eliminar.setActionCommand("Eliminar");
        btn_Eliminar.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Agregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Modificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Consulta, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Consulta;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Modificar;
    // End of variables declaration//GEN-END:variables

    
}
