
package Vista;

import Modelo.Producto;

public class JP_InformacionProdutos extends javax.swing.JPanel {

    /**
     * Creates new form JP_InformacionProdutos
     */
    public JP_InformacionProdutos() {
        initComponents();
        llenarTipo();
    }
    
    public void llenarTipo()
    {
        jsp_Tipo.removeAllItems();
        jsp_Tipo.addItem("Abarrotes");
        jsp_Tipo.addItem("Carnes");
        jsp_Tipo.addItem("Enlatados");
        jsp_Tipo.addItem("Gaseosas");
        jsp_Tipo.addItem("Jabones");
        jsp_Tipo.addItem("Verduras");
        
    }
    
   
    public String devolverCodigo()
    {
       return jt_Codigo.getText();
    }
     
    public void mostrarInformacion(Producto producto)
    {
 
        jt_Nombre.setText(producto.getNombre());
        jt_Descripcion.setText(producto.getDescripcion());
        jsp_Tipo.setSelectedItem(producto.getTipo());
        jt_PrecioCompra.setText(""+producto.getPrecioCompra());
        jt_PrecioVenta.setText(""+producto.getPrecioVenta());
        jsp_Cantidad.setValue(producto.getCantidad());
        jt_Codigo.setText(producto.getCodigo());
        
    }
    
    public void habilitarAgregar()
    {
        jt_Codigo.setEnabled(false);
        jt_Nombre.setEnabled(true);
        jt_Descripcion.setEnabled(true);
        jsp_Tipo.setEnabled(true);
        jt_PrecioCompra.setEnabled(true);
        jt_PrecioVenta.setEnabled(true);
        jsp_Cantidad.setEnabled(true);
    }
    
    public Producto devolverInformacion()
    {
        Producto producto = new Producto(jt_Codigo.getText(),jt_Nombre.getText(),jt_Descripcion.getText(),""+jsp_Tipo.getSelectedItem(),Integer.parseInt(""+jsp_Cantidad.getValue()),Double.parseDouble(jt_PrecioCompra.getText()),Double.parseDouble(jt_PrecioVenta.getText()));
        
        return producto;
    }
    
    public void estadoInicial()
    {
        jt_Codigo.setEnabled(true);
        jt_Nombre.setEnabled(false);
        jt_Descripcion.setEnabled(false);
        jsp_Tipo.setEnabled(false);
        jt_PrecioCompra.setEnabled(false);
        jt_PrecioVenta.setEnabled(false);
        jsp_Cantidad.setEnabled(false);
        
        jt_Codigo.setText("");
        jt_Nombre.setText("");
        jt_Descripcion.setText("");
        jsp_Tipo.setSelectedIndex(0);
        jt_PrecioCompra.setText("");
        jt_PrecioVenta.setText("");
        jsp_Cantidad.setValue(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Codigo = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jl_Descripcion = new javax.swing.JLabel();
        jl_Tipo = new javax.swing.JLabel();
        jl_Cantidad = new javax.swing.JLabel();
        jl_PrecioCompra = new javax.swing.JLabel();
        jl_PrecioVenta = new javax.swing.JLabel();
        jt_Codigo = new javax.swing.JTextField();
        jt_Nombre = new javax.swing.JTextField();
        jt_Descripcion = new javax.swing.JTextField();
        jsp_Tipo = new javax.swing.JComboBox();
        jsp_Cantidad = new javax.swing.JSpinner();
        jt_PrecioCompra = new javax.swing.JTextField();
        jt_PrecioVenta = new javax.swing.JTextField();

        jl_Codigo.setText("Codigo");

        jl_Nombre.setText("Nombre");

        jl_Descripcion.setText("Descripcion");

        jl_Tipo.setText("Tipo");

        jl_Cantidad.setText("Cantidad");

        jl_PrecioCompra.setText("Precio de Compra");

        jl_PrecioVenta.setText("Precio de Venta");

        jt_Nombre.setEnabled(false);
        jt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_NombreActionPerformed(evt);
            }
        });

        jt_Descripcion.setEnabled(false);

        jsp_Tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jsp_Tipo.setEnabled(false);

        jsp_Cantidad.setEnabled(false);

        jt_PrecioCompra.setEnabled(false);

        jt_PrecioVenta.setEnabled(false);
        jt_PrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_PrecioVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_PrecioCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_PrecioCompra))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_PrecioVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jt_PrecioVenta))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Codigo)
                            .addComponent(jl_Nombre)
                            .addComponent(jl_Descripcion)
                            .addComponent(jl_Tipo)
                            .addComponent(jl_Cantidad))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_Codigo)
                            .addComponent(jt_Nombre)
                            .addComponent(jt_Descripcion)
                            .addComponent(jsp_Tipo, 0, 187, Short.MAX_VALUE)
                            .addComponent(jsp_Cantidad))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Codigo)
                    .addComponent(jt_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre)
                    .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Descripcion)
                    .addComponent(jt_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Tipo)
                    .addComponent(jsp_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Cantidad)
                    .addComponent(jsp_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_PrecioCompra)
                    .addComponent(jt_PrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_PrecioVenta)
                    .addComponent(jt_PrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_PrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_PrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_PrecioVentaActionPerformed

    private void jt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_NombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_Cantidad;
    private javax.swing.JLabel jl_Codigo;
    private javax.swing.JLabel jl_Descripcion;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_PrecioCompra;
    private javax.swing.JLabel jl_PrecioVenta;
    private javax.swing.JLabel jl_Tipo;
    private javax.swing.JSpinner jsp_Cantidad;
    private javax.swing.JComboBox jsp_Tipo;
    private javax.swing.JTextField jt_Codigo;
    private javax.swing.JTextField jt_Descripcion;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_PrecioCompra;
    private javax.swing.JTextField jt_PrecioVenta;
    // End of variables declaration//GEN-END:variables
}
