
package Vista;

import Modelo.Proveedores;


public class JP_InformacionProveedores extends javax.swing.JPanel {

    /**
     * Creates new form JP_InformacionProveedores
     */
    public JP_InformacionProveedores() {
        initComponents();
    }

    public String devolverCedula()
    {
        return jt_Cedula.getText();
    }//Fin metodo devolverCedula
    
    public void mostrarInformacion(Proveedores provedor)
    {
        jt_Correo.setText(provedor.getCorreo());
        jt_NombreEmpresa.setText(provedor.getNombreEmpresa());
        jt_NombreContacto.setText(provedor.getNombreContacto());
        jt_Telefono.setText(provedor.getTelefono());
        jt_Cedula.setText(provedor.getCedula());
    }//Fin metodo mostrar informacion
    
    public void habilitarAgregar()
    {
    jt_Cedula.setEnabled(false);
    jt_Correo.setEnabled(true);
    jt_NombreContacto.setEnabled(true);
    jt_NombreEmpresa.setEnabled(true);
    jt_Telefono.setEnabled(true);
    }//Fin metodo habilitarAgregar
    
   public Proveedores devolverInformacion()
   {
    Proveedores provedor= new Proveedores(jt_Cedula.getText(),jt_NombreEmpresa.getText(),jt_Telefono.getText(),jt_Correo.getText(),jt_NombreContacto.getText());
     return provedor;
   }
    
    public void estadoInicial()
    {
    jt_Cedula.setEnabled(true);
    jt_Correo.setEnabled(false);
    jt_NombreContacto.setEnabled(false);
    jt_NombreEmpresa.setEnabled(false);
    jt_Telefono.setEnabled(false);
    
    
    jt_Cedula.setText("");
    jt_Correo.setText("");
    jt_NombreEmpresa.setText("");
    jt_NombreContacto.setText("");
    jt_Telefono.setText("");
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Cedula = new javax.swing.JLabel();
        jl_NombreEmpresa = new javax.swing.JLabel();
        jl_Telefono = new javax.swing.JLabel();
        jl_Correo = new javax.swing.JLabel();
        jl_NombreContacto = new javax.swing.JLabel();
        jt_Cedula = new javax.swing.JTextField();
        jt_NombreEmpresa = new javax.swing.JTextField();
        jt_Telefono = new javax.swing.JTextField();
        jt_Correo = new javax.swing.JTextField();
        jt_NombreContacto = new javax.swing.JTextField();

        jl_Cedula.setText("Cedula");

        jl_NombreEmpresa.setText("Nombre Empresa");

        jl_Telefono.setText("Telefono");

        jl_Correo.setText("Correo");

        jl_NombreContacto.setText("Nombre contacto");

        jt_NombreEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_NombreEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_Cedula)
                    .addComponent(jl_NombreEmpresa)
                    .addComponent(jl_Telefono)
                    .addComponent(jl_Correo)
                    .addComponent(jl_NombreContacto))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jt_Cedula)
                    .addComponent(jt_NombreEmpresa)
                    .addComponent(jt_Telefono)
                    .addComponent(jt_Correo)
                    .addComponent(jt_NombreContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Cedula)
                    .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NombreEmpresa)
                    .addComponent(jt_NombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Telefono)
                    .addComponent(jt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Correo)
                    .addComponent(jt_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NombreContacto)
                    .addComponent(jt_NombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_NombreEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_NombreEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_NombreEmpresaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_Cedula;
    private javax.swing.JLabel jl_Correo;
    private javax.swing.JLabel jl_NombreContacto;
    private javax.swing.JLabel jl_NombreEmpresa;
    private javax.swing.JLabel jl_Telefono;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_Correo;
    private javax.swing.JTextField jt_NombreContacto;
    private javax.swing.JTextField jt_NombreEmpresa;
    private javax.swing.JTextField jt_Telefono;
    // End of variables declaration//GEN-END:variables
}
